2024-02-29 16:33:42,945 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 495, in on_btnConfirm_clicked
    self.selectMysql(time, item_type, doctor, depart)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 332, in selectMysql
    self.time_list.append(q.value(3).strftime("%Y-%m-%d") + " " + q.value(9))
AttributeError: 'str' object has no attribute 'strftime'

2024-02-29 16:33:42,955 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 495, in on_btnConfirm_clicked
    self.selectMysql(time, item_type, doctor, depart)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 332, in selectMysql
    self.time_list.append(q.value(3).strftime("%Y-%m-%d") + " " + q.value(9))
AttributeError: 'str' object has no attribute 'strftime'

2024-02-29 16:35:53,231 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 453, in on_btnReturn_clicked
    if self.info == 201:
AttributeError: 'DataPage' object has no attribute 'info'

2024-02-29 16:35:53,235 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 453, in on_btnReturn_clicked
    if self.info == 201:
AttributeError: 'DataPage' object has no attribute 'info'

2024-02-29 16:37:55,461 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 453, in on_btnReturn_clicked
    if self.info == 201:
AttributeError: 'DataPage' object has no attribute 'info'

2024-02-29 16:37:55,463 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 453, in on_btnReturn_clicked
    if self.info == 201:
AttributeError: 'DataPage' object has no attribute 'info'

2024-02-29 16:38:11,789 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 453, in on_btnReturn_clicked
    if self.info == 201:
AttributeError: 'DataPage' object has no attribute 'info'

2024-02-29 16:38:11,792 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 453, in on_btnReturn_clicked
    if self.info == 201:
AttributeError: 'DataPage' object has no attribute 'info'

2024-02-29 17:21:49,475 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 301, in showCurrentTime
    def showCurrentTime(self) -> None:
KeyboardInterrupt

2024-02-29 17:21:49,475 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 301, in showCurrentTime
    def showCurrentTime(self) -> None:
KeyboardInterrupt

2024-02-29 18:34:14,651 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 254, in changePage
    self.cur_page = globals()[msg]()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 36, in __init__
    self.InitUI()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 53, in InitUI
    self.setTableWidget()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 270, in setTableWidget
    text = MyReport().gethtml()
TypeError: gethtml() missing 3 required positional arguments: 'item_type', 'reagent_info', and 'nature_aver_str'

2024-02-29 18:34:24,999 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 254, in changePage
    self.cur_page = globals()[msg]()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 36, in __init__
    self.InitUI()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 53, in InitUI
    self.setTableWidget()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 270, in setTableWidget
    text = MyReport().gethtml()
TypeError: gethtml() missing 3 required positional arguments: 'item_type', 'reagent_info', and 'nature_aver_str'

2024-02-29 18:35:08,338 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 186, in getData
    self.insertMysql(name_pic, cur_time)  # 图片数据信息存入数据库
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 235, in insertMysql
    connection = pymysql.connect(host="127.0.0.1", user="root", password="password", port=3306, database="test",
NameError: name 'pymysql' is not defined

2024-02-29 18:35:08,341 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 186, in getData
    self.insertMysql(name_pic, cur_time)  # 图片数据信息存入数据库
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 235, in insertMysql
    connection = pymysql.connect(host="127.0.0.1", user="root", password="password", port=3306, database="test",
NameError: name 'pymysql' is not defined

2024-02-29 18:50:44,529 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 186, in getData
    self.insertMysql(name_pic, cur_time)  # 图片数据信息存入数据库
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 235, in insertMysql
    connection = pymysql.connect(host="127.0.0.1", user="root", password="password", port=3306, database="test",
NameError: name 'pymysql' is not defined

2024-02-29 18:50:44,531 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 186, in getData
    self.insertMysql(name_pic, cur_time)  # 图片数据信息存入数据库
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 235, in insertMysql
    connection = pymysql.connect(host="127.0.0.1", user="root", password="password", port=3306, database="test",
NameError: name 'pymysql' is not defined

2024-02-29 18:54:57,949 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:54:57,949 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:54:59,323 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:54:59,323 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:00,959 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:00,959 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:04,911 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:04,911 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:05,478 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:05,478 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:05,629 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:05,629 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:05,810 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:55:05,810 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoginPage.py", line 180, in on_loginBtn_clicked
    print("send msg")
OSError: [Errno 22] Invalid argument

2024-02-29 18:56:43,369 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 186, in getData
    self.insertMysql(name_pic, cur_time)  # 图片数据信息存入数据库
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 235, in insertMysql
    connection = pymysql.connect(host="127.0.0.1", user="root", password="password", port=3306, database="test",
NameError: name 'pymysql' is not defined

2024-02-29 18:56:43,371 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 186, in getData
    self.insertMysql(name_pic, cur_time)  # 图片数据信息存入数据库
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\DataPage.py", line 235, in insertMysql
    connection = pymysql.connect(host="127.0.0.1", user="root", password="password", port=3306, database="test",
NameError: name 'pymysql' is not defined

2024-02-29 18:58:39,699 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 152, in blinkIcon
    def blinkIcon(self) -> None:
KeyboardInterrupt

2024-02-29 18:58:39,702 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 152, in blinkIcon
    def blinkIcon(self) -> None:
KeyboardInterrupt

